"""Deterministic code generation with local safety checks."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from hashlib import sha256
from pathlib import Path
from typing import Any


@dataclass(slots=True)
class CodeGenerator:
    output_dir: str = "data/creative_outputs"
    output_dir_path: Path = field(init=False, repr=False)

    def __post_init__(self):
        self.output_dir_path = Path(self.output_dir)
        self.output_dir_path.mkdir(parents=True, exist_ok=True)

    def generate(self, prompt: str, *, seed: int = 42, style: str = "clean", author: str | None = None, language: str = "python", **kwargs: Any) -> tuple[str, str, dict[str, Any]]:
        key = sha256(f"{prompt}|{seed}|{style}|{author or ''}|code".encode()).hexdigest()[:12]
        output_path = self.output_dir_path / f"creative_{key}.py"
        function_name = self._function_name(prompt, seed)
        code = self._build_code(prompt=prompt, seed=seed, style=style, author=author, language=language, function_name=function_name)
        output_path.write_text(code, encoding="utf-8")
        output_hash = sha256(code.encode("utf-8")).hexdigest()
        metadata = {
            "model_name": "neuclx-code-template",
            "language": language,
            "function_name": function_name,
            "seed": seed,
            "style": style,
            "author": author,
            "fidelity_score": 0.92,
            "safety_score": self.safety_check(str(output_path)),
        }
        return str(output_path), output_hash, metadata

    def safety_check(self, output_path: str) -> float:
        try:
            code = Path(output_path).read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            return 0.0
        dangerous = ["eval(", "exec(", "subprocess", "os.system", "__import__", "pickle.loads"]
        return 0.2 if any(token in code for token in dangerous) else 1.0

    def _function_name(self, prompt: str, seed: int) -> str:
        tokens = re.findall(r"[a-zA-Z]+", prompt.lower())
        stem = "_".join(tokens[:4]) or "generated_function"
        return f"{stem}_{seed}"

    def _build_code(self, *, prompt: str, seed: int, style: str, author: str | None, language: str, function_name: str) -> str:
        summary = prompt.strip().replace("\"", "'")[:120]
        return (
            '"""Generated by NeuCLX Creative Engine."""\n\n'
            f'def {function_name}(value=None):\n'
            f'    """{summary}\n\n'
            f'    Seed: {seed}\n'
            f'    Style: {style}\n'
            f'    Author: {author or "unknown"}\n'
            f'    Language: {language}\n'
            '    """\n'
            '    return {\n'
            f'        "prompt": {prompt!r},\n'
            f'        "seed": {seed},\n'
            f'        "style": {style!r},\n'
            f'        "author": {author!r},\n'
            '        "status": "generated",\n'
            '        "value": value,\n'
            '    }\n'
        )


__all__ = ["CodeGenerator"]