"""Deterministic OBJ generation for a simple 3D/CAD artifact."""

from __future__ import annotations

from dataclasses import dataclass, field
from hashlib import sha256
from pathlib import Path
from typing import Any


@dataclass(slots=True)
class CADGenerator:
    output_dir: str = "data/creative_outputs"
    output_dir_path: Path = field(init=False, repr=False)

    def __post_init__(self):
        self.output_dir_path = Path(self.output_dir)
        self.output_dir_path.mkdir(parents=True, exist_ok=True)

    def generate(self, prompt: str, *, seed: int = 42, style: str = "clean", author: str | None = None, **kwargs: Any) -> tuple[str, str, dict[str, Any]]:
        key = sha256(f"{prompt}|{seed}|{style}|{author or ''}|cad".encode()).hexdigest()[:12]
        output_path = self.output_dir_path / f"creative_{key}.obj"
        obj_text = self._build_obj(prompt, seed, style, author)
        output_path.write_text(obj_text, encoding="utf-8")
        output_hash = sha256(obj_text.encode("utf-8")).hexdigest()
        metadata = {
            "model_name": "neuclx-cad-cube",
            "vertex_count": 8,
            "face_count": 6,
            "seed": seed,
            "style": style,
            "author": author,
            "safety_score": 1.0,
            "fidelity_score": 0.9,
        }
        return str(output_path), output_hash, metadata

    def safety_check(self, output_path: str) -> float:
        return 1.0 if Path(output_path).suffix.lower() == ".obj" else 0.3

    def _build_obj(self, prompt: str, seed: int, style: str, author: str | None) -> str:
        scale = 1.0 + ((seed % 7) / 10.0)
        return f"""# Generated by NeuCLX Creative Engine
# Prompt: {prompt}
# Seed: {seed}
# Style: {style}
# Author: {author or 'unknown'}
v {-scale} {-scale} {-scale}
v {scale} {-scale} {-scale}
v {scale} {scale} {-scale}
v {-scale} {scale} {-scale}
v {-scale} {-scale} {scale}
v {scale} {-scale} {scale}
v {scale} {scale} {scale}
v {-scale} {scale} {scale}
f 1 2 3 4
f 5 6 7 8
f 1 5 8 4
f 2 6 7 3
f 4 3 7 8
f 1 2 6 5
"""


__all__ = ["CADGenerator"]